- type: gameMapPool
  id: DefaultMapPoolImp
  maps:
  # WIZDEN MAPS
  - AmberImp
  - BagelImp
  - BoxImp
  - Cluster
  - CogImp
  - CoreImp
  - ElkridgeImp
  - GateImp
  - MarathonImp
  - OasisImp
  - PackedImp
  - PlasmaImp
  - ReachImp
  - SalternImp
  - TrainImp
  - Xeno #aka exo
  # IMP MAPS:
  - Banana
  - Bedlam
  - Boat
  - Hummingbird
  - Lilboat
  #- Monarch
  #- Luna
  - Pathway
  - Union
  - Whisper
  # DELTAV MAPS:
  - Submarine
  # HARMONY MAPS:
  - Barratry
  #- Eclipse
  # QUANTUM BLUE MAPS, MOVE THESE TO OUR OWN DEFAULT.YML. THE ONLY REASON I DIDN'T IS BECAUSE I'M TOO LAZY TO FIGURE OUT HOW TO MAKE ONE
  # AND HOW TO SET THIS FILE AS IGNORED
  # MOODOTSUKI CAN GET IT I'VE DECIDED. MAKE HER DO THE WORK NOT ME
  # OR MATT OR SAGE
  # OR HELL GET ME TO DO IT IN ANOTHER PR. I'M DOING THIS AT 10:30 AND I CANNOT BE ASSED TO PUT IN MORE WORK RN
  # BUT I COULD BE ASSED LATER
  # I DUNNO REMIND ME
  - Chibi
